trigger:
  - main # Triggers the pipeline on changes to the 'main' branch

pool:
  vmImage: "ubuntu-latest" # Specifies the use of the latest Ubuntu image for the build agent

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.x" # Specifies the Python version to use
      addToPath: true

  - script: |
      python -m venv env  # Creates a virtual environment
      source env/bin/activate  # Activates the virtual environment
      pip install --upgrade pip  # Upgrades pip
      pip install -r requirements.txt  # Installs dependencies
    displayName: "Set up Python environment and install dependencies"

  - script: |
      source env/bin/activate  # Activates the virtual environment
      python manage.py test  # Runs Django tests
    displayName: "Run tests"

  - script: |
      source env/bin/activate  # Activates the virtual environment
      python manage.py collectstatic --noinput  # Collects static files
    displayName: "Collect static files"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)" # Specifies the root folder
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip" # Defines the output archive file
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)" # Specifies the path to publish
      ArtifactName: "drop"
