trigger:
  - main # Adjust this to your specific branch

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.8"
      addToPath: true

  - script: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip
    displayName: "Set up Python environment"

  - script: |
      source .venv/bin/activate
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: |
      source .venv/bin/activate
      python manage.py collectstatic --noinput
    displayName: "Collect static files"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: "tar"
      archiveFile: "$(Build.ArtifactStagingDirectory)/drop.tar"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
