trigger:
  - main # Adjust this to your specific branch

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.9"
      addToPath: true

  - script: |
      python -m venv env
      source env/bin/activate
      pip install --upgrade pip
    displayName: "Set up Python environment"

  - script: |
      source env/bin/activate
      pip install -r requirements.txt
    displayName: "Install dependencies"

  - script: |
      source env/bin/activate
      python manage.py test
    displayName: "Run tests"

  - script: |
      source env/bin/activate
      python manage.py collectstatic --noinput
    displayName: "Collect static files"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(System.DefaultWorkingDirectory)"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip"
      replaceExistingArchive: true

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "drop"
